### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by joshuabaker** [mundschenk-at/php-typography#109] opened 2019-05-03 15:12 UTC
I’m seeing some odd output from PHP 7.3.

#### Code

```php
$settings = new \PHP_Typography\Settings();
$typography = new \PHP_Typography\PHP_Typography();

echo $typography->process('Adipiscing Vehicula Ridiculus Pharetra', $settings);
```

#### PHP 7.2 Output

```html
Adipiscing Vehicula Ridiculus&nbsp;Pharetra
```

#### PHP 7.3 Output

```html
A&nbsp;d&nbsp;i&nbsp;p&nbsp;­&nbsp;i&nbsp;s&nbsp;c&nbsp;­&nbsp;i&nbsp;n&nbsp;g&nbsp;V&nbsp;e&nbsp;h&nbsp;i&nbsp;c&nbsp;­&nbsp;u&nbsp;­&nbsp;l&nbsp;a&nbsp;R&nbsp;i&nbsp;d&nbsp;i&nbsp;c&nbsp;u&nbsp;­&nbsp;l&nbsp;u&nbsp;s&nbsp;P&nbsp;h&nbsp;a&nbsp;r&nbsp;e&nbsp;t&nbsp;r&nbsp;a&nbsp;nbsp;
```

**Comment by mundschenk-at** [comment] 2019-05-03 15:25
Anything else that might differ between the two versions? I've noticed that the Travis script did not include PHP 7.3, so I rectified that, but [the tests run fine](https://travis-ci.org/mundschenk-at/php-typography/jobs/527824396).

**Comment by mundschenk-at** [comment] 2019-05-05 06:28
@joshuabaker Can you please be a bit more specific about those two environments (extensions, settings)?

**Comment by joshuabaker** [comment] 2019-05-07 18:39
@mundschenk-at It’s stock MAMP Pro on macOS without anything extra enabled. Specific PHP version is PHP 7.3.1.

**Comment by mundschenk-at** [comment] 2019-05-07 18:56
@joshuabaker There's something wrong with your PHP installation.

```bash
$ php --version
PHP 7.3.5 (cli) (built: May  2 2019 12:40:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.3.5, Copyright (c) 1999-2018, by Zend Technologies

$ cat foo.php 
<?php

require "vendor/autoload.php";

$settings = new \PHP_Typography\Settings();
$typography = new \PHP_Typography\PHP_Typography();

echo htmlentities($typography->process('Adipiscing Vehicula Ridiculus Pharetra', $settings));
echo "\n";

$ php foo.php 
Adip&shy;isc&shy;ing Vehic&shy;u&shy;la Ridicu&shy;lus Pharetra
```

**Comment by joshuabaker** [comment] 2019-05-07 19:16
I’m getting the same output when using the same version in isolation, directly using MAMP’s PHP.

```
$ /Applications/MAMP/bin/php/php7.3.1/bin/php --version
PHP 7.3.1 (cli) (built: Feb  1 2019 12:26:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies

$ php test.php
Adip&shy;isc&shy;ing Vehic&shy;u&shy;la Ridicu&shy;lus Pharetra
```

There’s clearly something going on that’s impacting the library elsewhere in the codebase. Do you have any pointers as to what that might be?

**Comment by mundschenk-at** [comment] 2019-05-07 19:23
It's pretty weird, looks like something is almost (but not quite) letter-spacing the output. Can you give me some idea what kind of codebase we are talking about? In a WordPress environment, I'd say something is filtering your output, but that's of course not the case here. Maybe some strange parameters for libxml? (Of course `html5-php` should normalize all that.)

**Comment by joshuabaker** [comment] 2019-05-07 19:35
This is happening on a Craft CMS installation, which itself is based on Yii 2.

@khalwat mentions that there’s [others running into the same issue](https://github.com/nystudio107/craft-typogrify/issues/28#issuecomment-490220570).

**Comment by mundschenk-at** [comment] 2019-05-08 17:21
@joshuabaker Any new fibdings?

**Comment by joshuabaker** [comment] 2019-05-08 17:23
@mundschenk-at We‘ve put it down for now. Will report back here should we find anything.

**Comment by clarknelson** [comment] 2019-05-09 16:21
I am experiencing the same issue on my website

**Comment by mundschenk-at** [comment] 2019-05-09 16:53
Are you using Craft as well, @clarknelson?

**Comment by clarknelson** [comment] 2019-05-09 17:01
yes! I am using Craft 3.0.31, and the `nystudio107/craft-typogrify` package, but "nystudio107" (along with @joshuabaker) have determined that this package is the source of the issue

**Comment by mundschenk-at** [comment] 2019-05-09 17:04
Well no, some kind of interaction with the Craft codebase. Unfortunately, I know nothing about Craft and cannot reproduce the issue standalone (as documented in this issue). Bring me a minimal test case and I'll gladly fix any bug in PHP-Typography.

**Comment by joshuabaker** [comment] 2019-05-09 17:04
@clarknelson If you read back, this library works fine in PHP 7.3. There’s something happening in the Craft environment that seems to be causing these issues.

**Comment by mundschenk-at** [comment] 2019-05-09 17:08
@joshuabaker Can you get me a list of installed packages in your Craft environment? It has to be a file that included directly by the autoloader (i.e. containing functions), otherwise this would not happen when you run the minimal example in your Craft directory.

**Comment by clarknelson** [comment] 2019-05-09 17:17
here are my composer dependencies, maybe there is a common package with @joshuabaker 

```
"craftcms/cms": "^3.0.31",
"craftcms/redactor": "^2.1.6",
"craftcms/feed-me": "^4.0",
"verbb/expanded-singles": "^1.0.5",
"verbb/super-table": "^2.0.10",
"vlucas/phpdotenv": "^2.4.0",
"doublesecretagency/craft-cpcss": "^2.1.0",
"nystudio107/craft-seomatic": "^3.1",
"nystudio107/craft-retour": "^3.1",
"nystudio107/craft-typogrify": "^1.1"
```

**Comment by joshuabaker** [comment] 2019-05-09 18:15
@mundschenk-at Right. Got it. It’s not Craft per se.

#### Problem Source

Craft is adjusting PHP’s string methods in the [web bootstrap file](https://github.com/craftcms/cms/blob/ef64d302f884023b86d60b9d16d15f39a29e5826/bootstrap/web.php#L26).

```php
setlocale(
    LC_CTYPE,
    'C.UTF-8', // libc >= 2.13
    'C.utf8', // different spelling
    'en_US.UTF-8', // fallback to lowest common denominator
    'en_US.utf8' // different spelling for fallback
);
```

#### Test

```php
<?php

require_once 'vendor/autoload.php';

$settings = new \PHP_Typography\Settings();
$typography = new \PHP_Typography\PHP_Typography();


echo htmlentities($typography->process('Adipiscing Vehicula Ridiculus Pharetra', $settings)) . "\n";
// Adip&shy;isc&shy;ing Vehic&shy;u&shy;la Ridicu&shy;lus Pharetra


// Craft’s normalization
setlocale(
    LC_CTYPE,
    'C.UTF-8', // libc >= 2.13
    'C.utf8', // different spelling
    'en_US.UTF-8', // fallback to lowest common denominator
    'en_US.utf8' // different spelling for fallback
);


echo htmlentities($typography->process('Adipiscing Vehicula Ridiculus Pharetra', $settings)) . "\n";
// A&amp;nbsp;d&amp;nbsp;i&amp;nbsp;p&amp;nbsp;&shy;&amp;nbsp;i&amp;nbsp;s&amp;nbsp;c&amp;nbsp;&shy;&amp;nbsp;i&amp;nbsp;n&amp;nbsp;g&amp;nbsp;V&amp;nbsp;e&amp;nbsp;h&amp;nbsp;i&amp;nbsp;c&amp;nbsp;&shy;&amp;nbsp;u&amp;nbsp;&shy;&amp;nbsp;l&amp;nbsp;a&amp;nbsp;R&amp;nbsp;i&amp;nbsp;d&amp;nbsp;i&amp;nbsp;c&amp;nbsp;u&amp;nbsp;&shy;&amp;nbsp;l&amp;nbsp;u&amp;nbsp;s&amp;nbsp;P&amp;nbsp;h&amp;nbsp;a&amp;nbsp;r&amp;nbsp;e&amp;nbsp;t&amp;nbsp;r&amp;nbsp;a&amp;nbsp;
```

**Comment by angrybrad** [comment] 2019-05-13 17:29
Should be resovled in https://github.com/craftcms/cms/commit/8bf818a2e61a3468ab4630e45a9ad9ad42503975, which will be in the next release.

**Closed** 2019-05-13 17:31 UTC
Labels: bug
